name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_call:
    

env:
  ALIYUN_REGISTRY: '${{ secrets.ALIYUN_REGISTRY }}'
  ALIYUN_NAME_SPACE: '${{ secrets.ALIYUN_NAME_SPACE }}'
  ALIYUN_REGISTRY_USER: '${{ secrets.ALIYUN_REGISTRY_USER }}'
  ALIYUN_REGISTRY_PASSWORD: '${{ secrets.ALIYUN_REGISTRY_PASSWORD }}'
  DATABASE_URL: '${{ secrets.DATABASE_URL }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 登录至阿里云容器镜像服务
        run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

      - name: 构建容器镜像
        run: |
          image_name=$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/voguexus:latest
          docker build . --file Dockerfile --build-arg DATABASE_URL="$DATABASE_URL" --tag $image_name && docker push $image_name
